version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

  api:
    image: blog-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    networks:
      - mynetwork

networks:
  mynetwork:
